#! /bin/bash 
# Uncomment this for debugging.
#ECHO=echo

prog_dir=$(dirname $0)
production_dir=/var/www
data=$prog_dir/../masterdash/html

install_dir=${1:-"$production_dir"}
$ECHO mkdir -v -p $install_dir

$ECHO cp -vr $data $install_dir


